-- LexIndia ULTIMATE "ALL-IN-ONE" SETUP SCRIPT
-- This script will: 1. Cleanup old data -> 2. Build Perfect Architecture -> 3. Populate Seed Data
-- Run this ONCE in your Supabase SQL Editor for a 100% complete project!

-----------------------------------------------------------
-- PART 1: CLEANUP (NIUKE THE OLD ARCHITECTURE)
-----------------------------------------------------------
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user() CASCADE;
DROP TABLE IF EXISTS public.user_achievements CASCADE;
DROP TABLE IF EXISTS public.achievements CASCADE;
DROP TABLE IF EXISTS public.notifications CASCADE;
DROP TABLE IF EXISTS public.likes CASCADE;
DROP TABLE IF EXISTS public.comments CASCADE;
DROP TABLE IF EXISTS public.sync_logs CASCADE;
DROP TABLE IF EXISTS public.broadcasts CASCADE;
DROP TABLE IF EXISTS public.sessions CASCADE;
DROP TABLE IF EXISTS public.advisory_requests CASCADE;
DROP TABLE IF EXISTS public.forum_posts CASCADE;
DROP TABLE IF EXISTS public.forum_threads CASCADE;
DROP TABLE IF EXISTS public.bookmarks CASCADE;
DROP TABLE IF EXISTS public.quiz_results CASCADE;
DROP TABLE IF EXISTS public.questions CASCADE;
DROP TABLE IF EXISTS public.quizzes CASCADE;
DROP TABLE IF EXISTS public.articles CASCADE;
DROP TABLE IF EXISTS public.categories CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;
DROP TYPE IF EXISTS public.user_role CASCADE;
DROP TYPE IF EXISTS public.content_status CASCADE;

-----------------------------------------------------------
-- PART 2: PERFECT ARCHITECTURE (SCHEMA)
-----------------------------------------------------------
DO $$ BEGIN
    CREATE TYPE user_role AS ENUM ('citizen', 'educator', 'legal-expert', 'admin');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE content_status AS ENUM ('draft', 'under_review', 'published');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  username TEXT UNIQUE NOT NULL,
  full_name TEXT,
  avatar_url TEXT,
  role user_role DEFAULT 'citizen',
  bio TEXT,
  points INTEGER DEFAULT 0,
  phone TEXT,
  city TEXT,
  state TEXT,
  CONSTRAINT username_length CHECK (char_length(username) >= 3)
);

CREATE TABLE public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  description TEXT,
  slug TEXT UNIQUE NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE public.articles (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  description TEXT,
  excerpt TEXT,
  category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
  author_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  status content_status DEFAULT 'draft',
  views BIGINT DEFAULT 0,
  likes_count BIGINT DEFAULT 0,
  is_official BOOLEAN DEFAULT FALSE,
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE public.quizzes (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  difficulty TEXT CHECK (difficulty IN ('Beginner', 'Intermediate', 'Advanced')),
  category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
  author_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  time_limit_minutes INTEGER DEFAULT 10,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE public.questions (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  quiz_id UUID REFERENCES quizzes(id) ON DELETE CASCADE,
  question_text TEXT NOT NULL,
  options JSONB NOT NULL,
  correct_answer_index INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE public.quiz_results (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  quiz_id UUID REFERENCES quizzes(id) ON DELETE CASCADE,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  score INTEGER NOT NULL,
  total_questions INTEGER NOT NULL,
  completed_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE public.comments (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  article_id UUID REFERENCES articles(id) ON DELETE CASCADE,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE public.likes (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  content_id UUID NOT NULL,
  content_type TEXT NOT NULL,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  UNIQUE(content_id, content_type, user_id)
);

CREATE TABLE public.advisory_requests (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  citizen_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  expert_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  subject TEXT NOT NULL,
  query TEXT NOT NULL,
  response TEXT,
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE public.notifications (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  read BOOLEAN DEFAULT FALSE,
  link TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE public.achievements (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  description TEXT,
  icon_url TEXT,
  points_reward INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE public.user_achievements (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  achievement_id UUID REFERENCES achievements(id) ON DELETE CASCADE,
  earned_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  UNIQUE(user_id, achievement_id)
);

-- Identity Trigger
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
DECLARE
  base_username TEXT;
  final_username TEXT;
BEGIN
  base_username := split_part(new.email, '@', 1);
  final_username := base_username;
  INSERT INTO public.profiles (id, username, full_name, avatar_url, role)
  VALUES (
    new.id, 
    COALESCE(new.raw_user_meta_data->>'username', final_username), 
    COALESCE(new.raw_user_meta_data->>'full_name', 'Lex India User'), 
    new.raw_user_meta_data->>'avatar_url', 
    COALESCE((new.raw_user_meta_data->>'role')::user_role, 'citizen')
  )
  ON CONFLICT (id) DO UPDATE SET
    username = EXCLUDED.username,
    full_name = EXCLUDED.full_name;
  RETURN new;
EXCEPTION WHEN OTHERS THEN RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- Enable RLS
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE advisory_requests ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Profiles viewable by all." ON profiles FOR SELECT USING (true);
CREATE POLICY "Users update own profile." ON profiles FOR UPDATE USING (auth.uid() = id);
CREATE POLICY "View published articles." ON articles FOR SELECT USING (status = 'published');
CREATE POLICY "Admins manage all articles." ON articles FOR ALL USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));
CREATE POLICY "Categories viewable by all." ON categories FOR SELECT USING (true);

-----------------------------------------------------------
-- PART 3: SEED DATA (POPULATE THE DASHBOARD)
-----------------------------------------------------------
INSERT INTO public.categories (name, slug, description) VALUES
('Constitutional Law', 'constitutional-law', 'Exploring rights and the bedrock of Indian democracy.'),
('Criminal Justice', 'criminal-justice', 'Understanding procedures and the path to legal recourse.'),
('Civil Rights', 'civil-rights', 'Individual freedoms afford to every citizen.'),
('Digital Jurisprudence', 'digital-law', 'Technology, privacy, and cyber laws.'),
('Environmental Protection', 'environmental-law', 'Legal journey towards a sustainable future.');

INSERT INTO public.articles (title, description, content, category_id, status, is_official)
SELECT 'Fundamental Rights Guide', 'A deep dive into the Indian Preamble.', 'Essential legal knowledge...', c.id, 'published', TRUE
FROM public.categories c WHERE c.slug = 'constitutional-law' LIMIT 1;

INSERT INTO public.quizzes (title, description, difficulty, category_id)
SELECT 'Constitution 101', 'Test your knowledge.', 'Beginner', c.id
FROM public.categories c WHERE c.slug = 'constitutional-law' LIMIT 1;

INSERT INTO public.questions (quiz_id, question_text, options, correct_answer_index)
SELECT q.id, 'Who is known as the Father of the Indian Constitution?', '["Mahatma Gandhi", "Nehru", "Ambedkar", "Patel"]'::jsonb, 2
FROM public.quizzes q WHERE q.title = 'Constitution 101' LIMIT 1;

INSERT INTO public.achievements (name, description, points_reward, icon_url) VALUES
('Legal Scholar', 'Completed 5 constitutional quizzes.', 50, 'shield'),
('Civic Leader', 'Read all foundational articles.', 30, 'award');

-----------------------------------------------------------
-- MISSION COMPLETE!
-----------------------------------------------------------
